events {}

http {
  include /etc/nginx/mime.types;

  upstream backend {
    server server:3000;
  }

  server {
    listen 80;

    location ~ ^/execute {
      proxy_pass http://backend;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_read_timeout 60s;
    }

    location / {
      proxy_pass http://frontend:80;
    }
  }
}